exports.MatrixAssemblyItem = [
  { id: `ExternalID`, title: `ExternalID` },
  { id: `Item Name/Number`, title: `Item Name/Number` },
  { id: `Display Name/Code`, title: `Display Name/Code` },
  { id: `Vendor SKU`, title: `Vendor SKU` },
  { id: `Subsidiary`, title: `Subsidiary` },
  { id: `Class`, title: `Class` },
  { id: `Track Landed Cost`, title: `Track Landed Cost` },
  { id: `Costing Method `, title: `Costing Method ` },
  { id: `Cost Category`, title: `Cost Category` },
  { id: `Use Bins`, title: `Use Bins` },
  { id: `Replenishment Method`, title: `Replenishment Method` },
  { id: `Auto-Calculate Lead Time`, title: `Auto-Calculate Lead Time` },
  { id: `Manufacturer`, title: `Manufacturer` },
  { id: `MPN`, title: `MPN` },
  { id: `Vendor 1 Name`, title: `Vendor 1 Name` },
  { id: `Cost Estimate Type`, title: `Cost Estimate Type` },
  { id: `Item Weight`, title: `Item Weight` },
  { id: `Weight Unit`, title: `Weight Unit` },
  { id: `Tax Schedule`, title: `Tax Schedule` },
  { id: `UPC Code`, title: `UPC Code` },
  { id: `Subitem of`, title: `Subitem of` },
  { id: `Matrix Type`, title: `Matrix Type` },
  { id: `Matrix Option - Size`, title: `Matrix Option - Size` },
  { id: `Matrix Option - Fragrance`, title: `Matrix Option - Fragrance` },
  { id: `Matrix Option - Color`, title: `Matrix Option - Color` },
  { id: `Matrix Option - Eyelash`, title: `Matrix Option - Eyelash` },
  { id: `Matrix Option - Brush`, title: `Matrix Option - Brush` },
  { id: `Shopify Wholesale Product Handle`, title: `Shopify Wholesale Product Handle` },
  { id: `Shopify Wholesale Price`, title: `Shopify Wholesale Price` },
  { id: `Shopify Wholesale Compare At Price`, title: `Shopify Wholesale Compare At Price` },
  { id: `Shopify Wholesale Description`, title: `Shopify Wholesale Description` },
  { id: `Shopify Wholesale Tags`, title: `Shopify Wholesale Tags` },
  { id: `Shopify Retail Product Handle`, title: `Shopify Retail Product Handle` },
  { id: `Shopify Retail Price`, title: `Shopify Retail Price` },
  { id: `Shopify Retail Compare At Price`, title: `Shopify Retail Compare At Price` },
  { id: `Shopify Retail Description`, title: `Shopify Retail Description` },
  { id: `Shopify Retail Tags`, title: `Shopify Retail Tags` },
  { id: `Shopify Product Type`, title: `Shopify Product Type` },
  { id: `Shopify Requires Shipping`, title: `Shopify Requires Shipping` },
  { id: `Component 1 - Item`, title: `Component 1 - Item` },
  { id: `Component 1 - Quantity`, title: `Component 1 - Quantity` },
  { id: `Component 2 - Item`, title: `Component 2 - Item` },
  { id: `Component 2 - Quantity`, title: `Component 2 - Quantity` },
  { id: `Component 3 - Item`, title: `Component 3 - Item` },
  { id: `Component 3 - Quantity`, title: `Component 3 - Quantity` },
  { id: `Component 4 - Item`, title: `Component 4 - Item` },
  { id: `Component 4 - Quantity`, title: `Component 4 - Quantity` },
  { id: `Component 5 - Item`, title: `Component 5 - Item` },
  { id: `Component 5 - Quantity`, title: `Component 5 - Quantity` },
  { id: `Component 6 - Item`, title: `Component 6 - Item` },
  { id: `Component 6 - Quantity`, title: `Component 6 - Quantity` },
  { id: `Component 7 - Item`, title: `Component 7 - Item` },
  { id: `Component 7 - Quantity`, title: `Component 7 - Quantity` },
  { id: `Component 8 - Item`, title: `Component 8 - Item` },
  { id: `Component 8 - Quantity`, title: `Component 8 - Quantity` },
  { id: `Component 9 - Item`, title: `Component 9 - Item` },
  { id: `Component 9 - Quantity`, title: `Component 9 - Quantity` },
  { id: `Component 10 - Item`, title: `Component 10 - Item` },
  { id: `Component 10 - Quantity`, title: `Component 10 - Quantity` },
  { id: `Component 11 - Item`, title: `Component 11 - Item` },
  { id: `Component 11 - Quantity`, title: `Component 11 - Quantity` },
  { id: `Component 12 - Item`, title: `Component 12 - Item` },
  { id: `Component 12 - Quantity`, title: `Component 12 - Quantity` },
  { id: `Component 13 - Item`, title: `Component 13 - Item` },
  { id: `Component 13 - Quantity`, title: `Component 13 - Quantity` },
  { id: `Component 14 - Item`, title: `Component 14 - Item` },
  { id: `Component 14 - Quantity`, title: `Component 14 - Quantity` },
  { id: `Component 15 - Item`, title: `Component 15 - Item` },
  { id: `Component 15 - Quantity`, title: `Component 15 - Quantity` },
  { id: `Component 16 - Item`, title: `Component 16 - Item` },
  { id: `Component 16 - Quantity`, title: `Component 16 - Quantity` },
  { id: `Component 17 - Item`, title: `Component 17 - Item` },
  { id: `Component 17 - Quantity`, title: `Component 17 - Quantity` },
  { id: `Component 18 - Item`, title: `Component 18 - Item` },
  { id: `Component 18 - Quantity`, title: `Component 18 - Quantity` },
  { id: `Component 19 - Item`, title: `Component 19 - Item` },
  { id: `Component 19 - Quantity`, title: `Component 19 - Quantity` },
  { id: `Component 20 - Item`, title: `Component 20 - Item` },
  { id: `Component 20 - Quantity`, title: `Component 20 - Quantity` },
  { id: `Component 21 - Item`, title: `Component 21 - Item` },
  { id: `Component 21 - Quantity`, title: `Component 21 - Quantity` },
  { id: `Component 22 - Item`, title: `Component 22 - Item` },
  { id: `Component 22 - Quantity`, title: `Component 22 - Quantity` },
  { id: `Component 23 - Item`, title: `Component 23 - Item` },
  { id: `Component 23 - Quantity`, title: `Component 23 - Quantity` },
  { id: `Component 24 - Item`, title: `Component 24 - Item` },
  { id: `Component 24 - Quantity`, title: `Component 24 - Quantity` },
  { id: `Component 25 - Item`, title: `Component 25 - Item` },
  { id: `Component 25 - Quantity`, title: `Component 25 - Quantity` },
  { id: `Component 26 - Item`, title: `Component 26 - Item` },
  { id: `Component 26 - Quantity`, title: `Component 26 - Quantity` },
  { id: `Component 27 - Item`, title: `Component 27 - Item` },
  { id: `Component 27 - Quantity`, title: `Component 27 - Quantity` },
  { id: `Component 28 - Item`, title: `Component 28 - Item` },
  { id: `Component 28 - Quantity`, title: `Component 28 - Quantity` },
  { id: `Component 29 - Item`, title: `Component 29 - Item` },
  { id: `Component 29 - Quantity`, title: `Component 29 - Quantity` },
  { id: `Component 30 - Item`, title: `Component 30 - Item` },
  { id: `Component 30 - Quantity`, title: `Component 30 - Quantity` }
];

exports.MatrixItem = [
  { id: `ExternalID`, title: `ExternalID` },
  { id: `Item Name/Number`, title: `Item Name/Number` },
  { id: `Display Name/Code`, title: `Display Name/Code` },
  { id: `Vendor SKU`, title: `Vendor SKU` },
  { id: `Subsidiary`, title: `Subsidiary` },
  { id: `Class`, title: `Class` },
  { id: `Track Landed Cost`, title: `Track Landed Cost` },
  { id: `Costing Method `, title: `Costing Method ` },
  { id: `Cost Category`, title: `Cost Category` },
  { id: `Use Bins`, title: `Use Bins` },
  { id: `Replenishment Method`, title: `Replenishment Method` },
  { id: `Auto-Calculate Lead Time`, title: `Auto-Calculate Lead Time` },
  { id: `Manufacturer`, title: `Manufacturer` },
  { id: `MPN`, title: `MPN` },
  { id: `Vendor 1 Name`, title: `Vendor 1 Name` },
  { id: `Cost Estimate Type`, title: `Cost Estimate Type` },
  { id: `Item Weight`, title: `Item Weight` },
  { id: `Weight Unit`, title: `Weight Unit` },
  { id: `Tax Schedule`, title: `Tax Schedule` },
  { id: `UPC Code`, title: `UPC Code` },
  { id: `Subitem of`, title: `Subitem of` },
  { id: `Matrix Type`, title: `Matrix Type` },
  { id: `Matrix Option - Size`, title: `Matrix Option - Size` },
  { id: `Matrix Option - Fragrance`, title: `Matrix Option - Fragrance` },
  { id: `Matrix Option - Color`, title: `Matrix Option - Color` },
  { id: `Matrix Option - Eyelash`, title: `Matrix Option - Eyelash` },
  { id: `Matrix Option - Brush`, title: `Matrix Option - Brush` },
  { id: `Shopify Wholesale Product Handle`, title: `Shopify Wholesale Product Handle` },
  { id: `Shopify Wholesale Price`, title: `Shopify Wholesale Price` },
  { id: `Shopify Wholesale Compare At Price`, title: `Shopify Wholesale Compare At Price` },
  { id: `Shopify Wholesale Description`, title: `Shopify Wholesale Description` },
  { id: `Shopify Wholesale Tags`, title: `Shopify Wholesale Tags` },
  { id: `Shopify Retail Product Handle`, title: `Shopify Retail Product Handle` },
  { id: `Shopify Retail Price`, title: `Shopify Retail Price` },
  { id: `Shopify Retail Compare At Price`, title: `Shopify Retail Compare At Price` },
  { id: `Shopify Retail Description`, title: `Shopify Retail Description` },
  { id: `Shopify Retail Tags`, title: `Shopify Retail Tags` },
  { id: `Shopify Product Type`, title: `Shopify Product Type` },
  { id: `Shopify Requires Shipping`, title: `Shopify Requires Shipping` }
];

exports.AssemblyItem = [
  { id: `ExternalID`, title: `ExternalID` },
  { id: `Item Name/Number`, title: `Item Name/Number` },
  { id: `Display Name/Code`, title: `Display Name/Code` },
  { id: `Vendor SKU`, title: `Vendor SKU` },
  { id: `Subsidiary`, title: `Subsidiary` },
  { id: `Class`, title: `Class` },
  { id: `Track Landed Cost`, title: `Track Landed Cost` },
  { id: `Costing Method `, title: `Costing Method ` },
  { id: `Cost Category`, title: `Cost Category` },
  { id: `Use Bins`, title: `Use Bins` },
  { id: `Replenishment Method`, title: `Replenishment Method` },
  { id: `Auto-Calculate Lead Time`, title: `Auto-Calculate Lead Time` },
  { id: `Manufacturer`, title: `Manufacturer` },
  { id: `MPN`, title: `MPN` },
  { id: `Vendor 1 Name`, title: `Vendor 1 Name` },
  { id: `Cost Estimate Type`, title: `Cost Estimate Type` },
  { id: `Item Weight`, title: `Item Weight` },
  { id: `Weight Unit`, title: `Weight Unit` },
  { id: `Tax Schedule`, title: `Tax Schedule` },
  { id: `UPC Code`, title: `UPC Code` },
  { id: `Shopify Wholesale Product Handle`, title: `Shopify Wholesale Product Handle` },
  { id: `Shopify Wholesale Price`, title: `Shopify Wholesale Price` },
  { id: `Shopify Wholesale Compare At Price`, title: `Shopify Wholesale Compare At Price` },
  { id: `Shopify Wholesale Description`, title: `Shopify Wholesale Description` },
  { id: `Shopify Wholesale Tags`, title: `Shopify Wholesale Tags` },
  { id: `Shopify Retail Product Handle`, title: `Shopify Retail Product Handle` },
  { id: `Shopify Retail Price`, title: `Shopify Retail Price` },
  { id: `Shopify Retail Compare At Price`, title: `Shopify Retail Compare At Price` },
  { id: `Shopify Retail Description`, title: `Shopify Retail Description` },
  { id: `Shopify Retail Tags`, title: `Shopify Retail Tags` },
  { id: `Shopify Product Type`, title: `Shopify Product Type` },
  { id: `Shopify Requires Shipping`, title: `Shopify Requires Shipping` },
  { id: `Component 1 - Item`, title: `Component 1 - Item` },
  { id: `Component 1 - Quantity`, title: `Component 1 - Quantity` },
  { id: `Component 2 - Item`, title: `Component 2 - Item` },
  { id: `Component 2 - Quantity`, title: `Component 2 - Quantity` },
  { id: `Component 3 - Item`, title: `Component 3 - Item` },
  { id: `Component 3 - Quantity`, title: `Component 3 - Quantity` },
  { id: `Component 4 - Item`, title: `Component 4 - Item` },
  { id: `Component 4 - Quantity`, title: `Component 4 - Quantity` },
  { id: `Component 5 - Item`, title: `Component 5 - Item` },
  { id: `Component 5 - Quantity`, title: `Component 5 - Quantity` },
  { id: `Component 6 - Item`, title: `Component 6 - Item` },
  { id: `Component 6 - Quantity`, title: `Component 6 - Quantity` },
  { id: `Component 7 - Item`, title: `Component 7 - Item` },
  { id: `Component 7 - Quantity`, title: `Component 7 - Quantity` },
  { id: `Component 8 - Item`, title: `Component 8 - Item` },
  { id: `Component 8 - Quantity`, title: `Component 8 - Quantity` },
  { id: `Component 9 - Item`, title: `Component 9 - Item` },
  { id: `Component 9 - Quantity`, title: `Component 9 - Quantity` },
  { id: `Component 10 - Item`, title: `Component 10 - Item` },
  { id: `Component 10 - Quantity`, title: `Component 10 - Quantity` },
  { id: `Component 11 - Item`, title: `Component 11 - Item` },
  { id: `Component 11 - Quantity`, title: `Component 11 - Quantity` },
  { id: `Component 12 - Item`, title: `Component 12 - Item` },
  { id: `Component 12 - Quantity`, title: `Component 12 - Quantity` },
  { id: `Component 13 - Item`, title: `Component 13 - Item` },
  { id: `Component 13 - Quantity`, title: `Component 13 - Quantity` },
  { id: `Component 14 - Item`, title: `Component 14 - Item` },
  { id: `Component 14 - Quantity`, title: `Component 14 - Quantity` },
  { id: `Component 15 - Item`, title: `Component 15 - Item` },
  { id: `Component 15 - Quantity`, title: `Component 15 - Quantity` },
  { id: `Component 16 - Item`, title: `Component 16 - Item` },
  { id: `Component 16 - Quantity`, title: `Component 16 - Quantity` },
  { id: `Component 17 - Item`, title: `Component 17 - Item` },
  { id: `Component 17 - Quantity`, title: `Component 17 - Quantity` },
  { id: `Component 18 - Item`, title: `Component 18 - Item` },
  { id: `Component 18 - Quantity`, title: `Component 18 - Quantity` },
  { id: `Component 19 - Item`, title: `Component 19 - Item` },
  { id: `Component 19 - Quantity`, title: `Component 19 - Quantity` },
  { id: `Component 20 - Item`, title: `Component 20 - Item` },
  { id: `Component 20 - Quantity`, title: `Component 20 - Quantity` },
  { id: `Component 21 - Item`, title: `Component 21 - Item` },
  { id: `Component 21 - Quantity`, title: `Component 21 - Quantity` },
  { id: `Component 22 - Item`, title: `Component 22 - Item` },
  { id: `Component 22 - Quantity`, title: `Component 22 - Quantity` },
  { id: `Component 23 - Item`, title: `Component 23 - Item` },
  { id: `Component 23 - Quantity`, title: `Component 23 - Quantity` },
  { id: `Component 24 - Item`, title: `Component 24 - Item` },
  { id: `Component 24 - Quantity`, title: `Component 24 - Quantity` },
  { id: `Component 25 - Item`, title: `Component 25 - Item` },
  { id: `Component 25 - Quantity`, title: `Component 25 - Quantity` },
  { id: `Component 26 - Item`, title: `Component 26 - Item` },
  { id: `Component 26 - Quantity`, title: `Component 26 - Quantity` },
  { id: `Component 27 - Item`, title: `Component 27 - Item` },
  { id: `Component 27 - Quantity`, title: `Component 27 - Quantity` },
  { id: `Component 28 - Item`, title: `Component 28 - Item` },
  { id: `Component 28 - Quantity`, title: `Component 28 - Quantity` },
  { id: `Component 29 - Item`, title: `Component 29 - Item` },
  { id: `Component 29 - Quantity`, title: `Component 29 - Quantity` },
  { id: `Component 30 - Item`, title: `Component 30 - Item` },
  { id: `Component 30 - Quantity`, title: `Component 30 - Quantity` }
];

exports.InventoryItem = [
  { id: `ExternalID`, title: `ExternalID` },
  { id: `Item Name/Number`, title: `Item Name/Number` },
  { id: `Display Name/Code`, title: `Display Name/Code` },
  { id: `Vendor SKU`, title: `Vendor SKU` },
  { id: `Subsidiary`, title: `Subsidiary` },
  { id: `Class`, title: `Class` },
  { id: `Track Landed Cost`, title: `Track Landed Cost` },
  { id: `Costing Method `, title: `Costing Method ` },
  { id: `Cost Category`, title: `Cost Category` },
  { id: `Use Bins`, title: `Use Bins` },
  { id: `Replenishment Method`, title: `Replenishment Method` },
  { id: `Auto-Calculate Lead Time`, title: `Auto-Calculate Lead Time` },
  { id: `Manufacturer`, title: `Manufacturer` },
  { id: `MPN`, title: `MPN` },
  { id: `Vendor 1 Name`, title: `Vendor 1 Name` },
  { id: `Cost Estimate Type`, title: `Cost Estimate Type` },
  { id: `Item Weight`, title: `Item Weight` },
  { id: `Weight Unit`, title: `Weight Unit` },
  { id: `Tax Schedule`, title: `Tax Schedule` },
  { id: `UPC Code`, title: `UPC Code` },
  { id: `Shopify Wholesale Product Handle`, title: `Shopify Wholesale Product Handle` },
  { id: `Shopify Wholesale Price`, title: `Shopify Wholesale Price` },
  { id: `Shopify Wholesale Compare At Price`, title: `Shopify Wholesale Compare At Price` },
  { id: `Shopify Wholesale Description`, title: `Shopify Wholesale Description` },
  { id: `Shopify Wholesale Tags`, title: `Shopify Wholesale Tags` },
  { id: `Shopify Retail Product Handle`, title: `Shopify Retail Product Handle` },
  { id: `Shopify Retail Price`, title: `Shopify Retail Price` },
  { id: `Shopify Retail Compare At Price`, title: `Shopify Retail Compare At Price` },
  { id: `Shopify Retail Description`, title: `Shopify Retail Description` },
  { id: `Shopify Retail Tags`, title: `Shopify Retail Tags` },
  { id: `Shopify Product Type`, title: `Shopify Product Type` },
  { id: `Shopify Requires Shipping`, title: `Shopify Requires Shipping` }
];